### PR TITLE
Sle15 sp1 update

### PR DESCRIPTION
**Pull request by noelpower**
## Problem

* Package doesn't build on SLE-15-SP1

- https://bugzilla.suse.com/show_bug.cgi?id=1197865

## Solution
Update package spec

### CODE REVIEW

**Comment by noelpower** [comment]
lets not do merge this until we decide what we are doing

**Review by scabrero — APPROVED** [review]
LGTM.

**Comment by dgdavid** [comment]
Hi guys!

Please, excuse us. Quite busy months and the PR has been out of sight for a couple of months. @scabrero, shall I push the merge button?

**Comment by noelpower** [comment]
I think we will leave this for the moment, this feature is deprecated anyway (and the need for the package to build on sle15-sp4 has been satisfied by forking) If we need we can always resurrect this

**Pull request closed without merging**
